-- Buffer tri-state --
LIBRARY ieee;
USE ieee.std_logic_1164.all;

ENTITY BUFF IS
	PORT (BUFF_IN		:		IN STD_LOGIC_VECTOR(3 DOWNTO 0);
			ENABLE		:		IN STD_LOGIC;
			BUFF_OUT		:		OUT STD_LOGIC_VECTOR(3 DOWNTO 0));
END BUFF;

ARCHITECTURE LOGIC OF BUFF IS
	BEGIN
		PROCESS(ENABLE)
		BEGIN
			IF ENABLE = '1' THEN
				BUFF_OUT <= BUFF_IN;
			END IF;
		END PROCESS;
END LOGIC;