LIBRARY ieee;
USE ieee.std_logic_1164.all;

PACKAGE BUFF_package IS
	COMPONENT BUFF
		PORT
		(
			BUFF_IN		:	 IN STD_LOGIC_VECTOR(3 DOWNTO 0);
			ENABLE		:	 IN STD_LOGIC;
			BUFF_OUT		:	 OUT STD_LOGIC_VECTOR(3 DOWNTO 0)
		);
	END COMPONENT;
END PACKAGE;