LIBRARY ieee;
USE ieee.std_logic_1164.all;

PACKAGE comp_package IS
	COMPONENT comp
		PORT
		(
			A		:	 IN STD_LOGIC_VECTOR(3 DOWNTO 0);
			B		:	 IN STD_LOGIC_VECTOR(3 DOWNTO 0);
			S		:	 OUT STD_LOGIC_VECTOR(3 DOWNTO 0)
		);
	END COMPONENT;
END PACKAGE;