LIBRARY ieee;
USE ieee.std_logic_1164.all;

PACKAGE CPU_package IS
	COMPONENT CPU
		PORT
		(
			CLK		:	 IN STD_LOGIC;
			ENABLE		:	 IN STD_LOGIC;
			OPREG		:	 IN STD_LOGIC_VECTOR(3 DOWNTO 0);
			OPCODE		:	 IN STD_LOGIC_VECTOR(3 DOWNTO 0);
			DATA		:	 IN STD_LOGIC_VECTOR(3 DOWNTO 0);
			CLEAR		:	 IN STD_LOGIC;
			R1		:	 OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
			R2		:	 OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
			R3		:	 OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
			R4		:	 OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
			OVERFLOW		:	 OUT STD_LOGIC;
			CBUS	:	OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
			EQ		:	OUT STD_LOGIC;
			GT		:	OUT STD_LOGIC;
			LT		:	OUT STD_LOGIC;
			ST		:	OUT STD_LOGIC_VECTOR(1 DOWNTO 0)
		);
	END COMPONENT;
END PACKAGE;