LIBRARY ieee;
USE ieee.std_logic_1164.all;

PACKAGE DECODER_package IS
	COMPONENT DECODER
		PORT
		(
			CLK		:	 IN STD_LOGIC;
			REG1		:	 IN STD_LOGIC_VECTOR(1 DOWNTO 0);
			REG2		:	 IN STD_LOGIC_VECTOR(1 DOWNTO 0);
			CLEAR		:	 IN STD_LOGIC;
			ENABLE	:   IN STD_LOGIC;
			OPCODE		:	 IN STD_LOGIC_VECTOR(2 DOWNTO 0);
			DATA		:	 IN STD_LOGIC_VECTOR(3 DOWNTO 0);
			S1		:	 OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
			S2		:	 OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
			R1		:		OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
			R2		:		OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
			R3		:		OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
			R4		:		OUT STD_LOGIC_VECTOR(3 DOWNTO 0)
		);
	END COMPONENT;
END PACKAGE;