LIBRARY ieee;
USE ieee.std_logic_1164.all;

PACKAGE mult_package IS
	COMPONENT mult
		PORT
		(
			A		:	 IN STD_LOGIC_VECTOR(1 DOWNTO 0);
			B		:	 IN STD_LOGIC_VECTOR(1 DOWNTO 0);
			P		:	 OUT STD_LOGIC_VECTOR(3 DOWNTO 0)
		);
	END COMPONENT;
END PACKAGE;