-- Registrador 4 bits com CLEAR --
LIBRARY ieee;
USE ieee.std_logic_1164.all;

ENTITY reg4 IS
	PORT (CLK			:		IN STD_LOGIC;
			REG_IN		:		IN STD_LOGIC_VECTOR(3 DOWNTO 0);
			CLEAR			:		IN STD_LOGIC;
			WR				:		IN STD_LOGIC;
			REG_OUT		:		OUT STD_LOGIC_VECTOR(3 DOWNTO 0));
END reg4;

ARCHITECTURE LOGIC OF reg4 IS
	BEGIN
	
		PROCESS(CLK, CLEAR, WR)
		BEGIN
			IF CLEAR = '1' THEN
				REG_OUT <= "0000";
			
			ELSIF CLK'EVENT AND CLK = '1' AND WR = '1' THEN
					REG_OUT <= REG_IN;	
			END IF;
		END PROCESS;
END LOGIC;