LIBRARY ieee;
USE ieee.std_logic_1164.all;

PACKAGE ripple_carry_package IS
	COMPONENT ripple_carry
		PORT
		(
			CIN		:	 IN STD_LOGIC;
			X		:	 IN STD_LOGIC_VECTOR(3 DOWNTO 0);
			Y		:	 IN STD_LOGIC_VECTOR(3 DOWNTO 0);
			S		:	 OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
			COUT		:	 OUT STD_LOGIC
		);
	END COMPONENT;
END PACKAGE;