LIBRARY ieee;
USE ieee.std_logic_1164.all;

PACKAGE ULA_package IS
	COMPONENT ULA
		PORT
		(
			OPCODE		:	 IN STD_LOGIC_VECTOR(3 DOWNTO 0);
			A		:	 IN STD_LOGIC_VECTOR(3 DOWNTO 0);
			B		:	 IN STD_LOGIC_VECTOR(3 DOWNTO 0);
			ENABLE	:	IN STD_LOGIC;
			S		:	 OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
			OVERFLOW		:	 OUT STD_LOGIC;
			EQ, GT, LT	:	OUT STD_LOGIC
		);
	END COMPONENT;
END PACKAGE;