LIBRARY ieee;
USE ieee.std_logic_1164.all;

-- Buffer 4 bits com CTRL como GATE --

ENTITY BUFF IS
	PORT (BUFF_IN	:	IN STD_LOGIC_VECTOR(3 DOWNTO 0);
			CTRL		:	IN STD_LOGIC;
			BUFF_OUT	:	OUT STD_LOGIC_VECTOR(3 DOWNTO 0));
END BUFF;

ARCHITECTURE LOGIC OF BUFF IS
	BEGIN
		PROCESS(CTRL)
		BEGIN
			IF CTRL = '1' THEN
				BUFF_OUT <= BUFF_IN;
			END IF;
		END PROCESS;
		
END LOGIC;