LIBRARY ieee;
USE ieee.std_logic_1164.all;

PACKAGE CPU_package IS
	COMPONENT CPU
		PORT
		(
			DATA		:	 IN STD_LOGIC_VECTOR(3 DOWNTO 0);
			CLK		:	 IN STD_LOGIC;
			ENABLE		:	 IN STD_LOGIC;
			RESET		:	 IN STD_LOGIC;
			F		:	 IN STD_LOGIC_VECTOR(2 DOWNTO 0);
			REG1_OUT		:	 OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
			REG2_OUT		:	 OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
			REG3_OUT		:	 OUT STD_LOGIC_VECTOR(3 DOWNTO 0)
		);
	END COMPONENT;
END PACKAGE;