LIBRARY ieee;
USE ieee.std_logic_1164.all;

PACKAGE CPU_FINAL_package IS
	COMPONENT CPU_FINAL
		PORT
		(
			SW		:	 IN STD_LOGIC_VECTOR(8 DOWNTO 0);
			Clock_50		:	 IN STD_LOGIC;
			HEX6		:	 OUT STD_LOGIC_VECTOR(0 TO 6);
			HEX4		:	 OUT STD_LOGIC_VECTOR(0 TO 6);
			HEX3		:	 OUT STD_LOGIC_VECTOR(0 TO 6)
		);
	END COMPONENT;
END PACKAGE;