LIBRARY ieee;
USE ieee.std_logic_1164.all;

PACKAGE REG4_package IS
	COMPONENT REG4
		PORT
		(
			REG_IN		:	 IN STD_LOGIC_VECTOR(3 DOWNTO 0);
			CLK		:	 IN STD_LOGIC;
			CLEAR		:	 IN STD_LOGIC;
			REG_OUT		:	 OUT STD_LOGIC_VECTOR(3 DOWNTO 0)
		);
	END COMPONENT;
END PACKAGE;